name: update_oosc_surveys

# Run script everyday at 01:00 UTC
on:
  schedule: 
    - cron: '0 1 * * *' 
  
jobs:
  update_oosc_surveys:
    runs-on: ubuntu-latest
    env:
      KOBOTOOLBOX_URL: 'kf.kobotoolbox.org/'
      KOBOTOOLBOX_TOKEN: ${{ secrets.OOSC_KOBO_TOKEN }}
    steps:
      - uses: actions/checkout@v3
      - uses: r-lib/actions/setup-r@v2
      - name: install_packages
      - name: Setup packages
        run: |
          source("00_setup.R")
        shell: Rscript {0} 
      - name: Update OOSC data
        run: |
          source("02_download_data_from_kobotoolbox.R")
        shell: Rscript {0} 
